version: "3"

services:
    proxy:
        image: nginx:latest
        volumes:
            - ${DIR}/proxy/nginx_templates:/etc/nginx/templates:ro
            - ${DIR}/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "3000:80"
        environment:
            - AUTH_API_PREFIX=${AUTH_API_PREFIX}
            - NGINX_PORT=80
        container_name: proxy
    auth:
        build:
            context: ${DIR}/api/auth
            dockerfile: ${DIR}/api/auth/Dockerfile
        volumes:
            - ${DIR}/api/auth:/auth
        
        container_name: auth
        environment:
            - AUTH_API_PREFIX=${AUTH_API_PREFIX}
            